name: Test
on: [push]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Test
      run: go test -v ./merkle